taxi_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'nyc') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'nyc') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'nyc_taxi') }}"
      schema: stg
      threads: "{{ env_var('DBT_THREADS', '4') | int }}"
